application: wtfconverter
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /js/chosen
  static_dir: js/chosen 
- url: /admin
  script: admin.app
- url: /admin/.*
  script: admin.app

- url: /.*
  script: convert.app

libraries:
- name: jinja2
  version: latest